# REGRAS:
# NÃO PODE TER 2 ANIMAIS COM O MSM CHIP
# TEM Q TER AS 3 VACINAS BASICAS (RAIVA, LEPTOSPIROSE, HEPATITE INFECCIOSA) PARA PODER SER ADOTADO


# VAI PRECISAR DE UM MÉTODO DE "BUSCAR ANIMAL" PRA PODER ADOTAR, DE PREFERENCIA PELO CHIP

# Tenta fazer 2 listas no init, uma com todos os animais ou só com os que não tem as vacinas basicas, 
# e outra com os que já podem ser adotados


# FAZER PRIMEIRO SÓ COM AS VACINAS NORMAL, 
# DEPOIS QUE ESTIVER TUDO PRONTO, SE DER TEMPO,
# TENTAR FAZER A PARTE DE ADD O DIA DA VACINAÇÃO (FORA DO OBJETO VACINA)
# POSSIVELMENTE COM UM DICIONÁRIO

